import sessions from "../data/sessions.json";
import apolloDatasource from "apollo-datasource";
const { DataSource } = apolloDatasource;
import lodash from "lodash";
const { _ } = lodash;

class SessionAPI extends DataSource {
	constructor() {
		super();
	}

	initialize(config) {
	}

	getSessions(args) {
		return _.filter(sessions, args);
	}

	getSessionById(id) {
		const session = _.filter(sessions, { id: parseInt(id) });
		return session[0];
	}
	
	// modify existing session attribute
	toggleFavouriteSession(id) {
		const session = _.filter(sessions, { id: parseInt(id) });
		session[0].favourite = !session[0].favourite;
		return session[0];
	}

	// add new data
	addSession(session){
		// id would generally be autogenerated by database incrementation, this is to illustrate the function
		session.id = 12;
		sessions.push(session);
		return session;
	}
}

export default SessionAPI;
